### ISSUE TITLE
Nhận xét bài tập tuần 2

### ISSUE THREAD

**Issue by ngodai** [phamvandac/thuctap#2]
- Không nên đặt tên biến trùng với tên hàm 
- Nên sử dụng con trỏ, Stack, Queue để giải quyết bài toán kiểu này(FIFO, LIFO...)

**Comment by phamvandac** [comment]
- Bài 1: Em đã sửa tên hàm
- Bài 2: Em sẽ cập nhật sau khi hoàn thành bài tuần 3. Em chưa chắc về con trỏ, stack,.. nhưng theo em nghĩ thì dùng cấu trúc dữ liệu stack sẽ tốn bộ nhớ hơn.
